In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt 

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/california-housing-prices/housing.csv


**Numpy**

In [2]:
# creating a 1D numpy array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
# array dimensions
a.ndim

1

In [4]:
# creating a 2D numpy array
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
b.ndim

2

In [6]:
# creating a 3D numpy array
c = np.array([[(1.4, 3, 5), (2.5, 5, 1)], [(1, 4, 6.1), (2, 4, 5)]], dtype=float)
c

array([[[1.4, 3. , 5. ],
        [2.5, 5. , 1. ]],

       [[1. , 4. , 6.1],
        [2. , 4. , 5. ]]])

In [7]:
c.ndim

3

In [8]:
# creating a numpy array consisting of 0's
z = np.zeros((3, 4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# creating a numpy array consisting of 1's
o = np.ones((2, 3, 4))
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
o.ndim

3

In [11]:
# creating an evenly spaced array with regular intervals
d = np.arrange(10, 25, 5)
d

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
# create an evenly spaced sequence with regular intervals
lp = np.linespace(0, 2, 9)
lp

In [ ]:
# create an array with 1's on the diagonal and 0's elsewhere
f = np.eye(2)
f

In [ ]:
# create an array of given shape with random values
e = np.empty((3, 2))
e

In [ ]:
# create an array with random values
r = np.random.random((2, 2))
r

In [ ]:
z = e.astype(int)
z.dtype

In [ ]:
# operations on a numpy array
s = np.array([(1, 2, 3.1), (3, 5, 2.8)], dtype=float)
print(s)
print(s.shape)
print(len(s))
print(s.ndim)
print(s.dtype.name)
s = s.astype(int)
print(s.dtype.name)
print(np.sum(s))
print(np.min(s))
print(np.max(s))
print(np.max(s, axis=0))
print(np.min(s, axis=1))
print(s.cumsum(axis=1))
print(np.mean(s))
print(np.median(s))
print(np.std(s))
print(np.transpose(s))
print(s.ravel())

In [ ]:
# change the shape of an array
b.reshape(2, 3)

In [ ]:
# vertically stack arrays
y = np.array([1, 2, 3])
t = np.vstack((y, b))
t

**Sklearn**

In [ ]:
# preprocessing
from sklearn import preprocessing, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
# labelencoder or onehot encoder
from sklearn.preprocessing import LabelEncoder
# supervised
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.svm import SVC, SVR
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import NearestNeighbors
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
# unsupervised
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [ ]:
# create an input array X with random values
X = np.random.random((10, 5,))
X

In [ ]:
# output labels
y = np.array(['M', 'M', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'M'])

In [ ]:
# if values in X are less than 0.7 set them to 0
X[X<0.7] = 0
X

In [ ]:
# convert output labels to numeric form
lbn = LabelEncoder()
y = lbn.fit_transform(y)

In [ ]:
# split the data into training and testing data (training data size=80%, testing data size=20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
print(f"X Training data shape: {X_train.shape}")
print(f"X Testing data shape: {X_test.shape}")
print(f"y Training data shape: {y_train.shape}")
print(f"y Testing data shape: {y_test.shape}")

In [ ]:
scaler = StandardScaler()

In [ ]:
# centering the values around the mean
X_std = scaler.fit_transform(X_train)
X_test_std = scaler.fit_transform(X_test)
print(X_std.mean())

In [ ]:
normal = Normalizer()

In [ ]:
# rescaling values to the range between 0 and 1
normal_X = normal.fit_transform(X_train)
normal_X_test = normal.transform(X_test)

In [ ]:
# training the MLP classifier model
mlp = MLPClassifier()
mlp.fit(X_std, y_train)
y_pred = mlp.predict(X_test_std)

In [ ]:
# evaluate the model
print(mlp.score(X_test_std, y_test))
print(y_pred)

**Pandas & Matplotlib**

In [ ]:
# reading the data
data = pd.read_csv('../input/california-housing-prices/housing.csv')

In [ ]:
# display first 5 rows
data.head()

In [ ]:
data.describe()

In [ ]:
data.count()

In [ ]:
# display NaN values
data.isna().sum()

In [ ]:
data.total_rooms[:10]

In [ ]:
# select a specific row
data.iloc[2]

In [ ]:
data.sort_values('total_rooms')

In [ ]:
data.total_rooms.unique()

In [ ]:
# display correlation matrix
data.corr()

In [ ]:
cols = data.columns
cols

In [ ]:
plt.matshow(data.corr())
plt.xticks(list(range(len(cols))), cols, rotation='vertical')
plt.yticks(list(range(len(cols))), cols, rotation='horizontal')
plt.colorbar()

In [ ]:
data.plot.box()

In [ ]:
plt.plot(data.total_rooms)

In [ ]:
plt.hist(data.total_rooms)

In [ ]:
data.plot()

In [ ]:
data.plot(subplots=True, figsize=(9,9))